### PR TITLE
Fixes for environment variables sent to components

### LINKED ISSUE #75: Environment variables not properly working when sent in spawn syscall
This issue is being solved in #74

### PR DESCRIPTION
**Pull request by pablocarle**
- `_CEE_ENVFILE*` are not sent downwards to the components to avoid conflicts.
- Send a memory copy of environment variable list.
- Fix to send environment variables for `zwe internal get-launch-components`

Resolve #75

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -705,6 +718,37 @@ static void *handle_comp_comm(void *args) {
...
+    env_records++;
+  }
+  
+  const char **env_comp = malloc(env_records + 1);
+
+  int i = 0;
+  char *aux = NULL;
+  for (char **env = shared_uss_env; *env != 0 && i < env_records; env++) {
+    char *thisEnv = *env;
+    aux = malloc(strlen(thisEnv) + 1);
```
Comment (pavel-jares-bcm) [inline src/main.c]:
```suggestion
  for (char **env = shared_uss_env; *env != 0 && i < env_records; env++) {
    char *thisEnv = *env;
    char *aux = malloc(strlen(thisEnv) + 1);
```

File: src/main.c [hunk 2]
```diff
@@ -705,6 +718,37 @@ static void *handle_comp_comm(void *args) {
...
+    strncpy(aux, thisEnv, strlen(thisEnv));
+    aux[strlen(thisEnv)] = 0;
```
Comment (pavel-jares-bcm) [inline src/main.c]:
```suggestion
```
function `strncpy is responsible for that.

File: src/main.c [hunk 3]
```diff
@@ -1227,10 +1272,67 @@ static void handle_get_component_line(void *data, const char *line) {
   }
 }
 
+static char* get_get_launch_components_cmd(char* sharedenv) {
```
Comment (pavel-jares-bcm) [inline src/main.c]:
```suggestion
static char* get_launch_components_cmd(char* sharedenv) {
```
Could we rename this method? See get_get_

File: src/main.c [hunk 4]
```diff
@@ -1227,10 +1272,67 @@ static void handle_get_component_line(void *data, const char *line) {
...
+      strcat(output, envName);
+      char *envValue = &thisEnv[strlen(envName) + 1];
+      if (*envValue == '"') { // Env value is already enclosed in quotes
+        strcat(output, "=");
+        strcat(output, envValue);
+        trimRight(output, strlen(output));
+        strcat(output, " ");
+      } else {
+        strcat(output, "=\"");
+        strcat(output, envValue);
```
Comment (pavel-jares-bcm) [inline src/main.c:1326]: Quetos are not escaped

File: src/main.c [hunk 5]
```diff
@@ -1227,10 +1272,67 @@ static void handle_get_component_line(void *data, const char *line) {
...
+    char *thisEnv = *env;
+    required += (strlen(thisEnv) + 3); // space + quotes
+  }
+
+  required++;
+  output = malloc(required);
+  aux = malloc(required);
+  for (char **env = shared_uss_env + 1; *env != 0; env++) { // First element is NULL, reserved to _BPX_SHAREAS
+    char *thisEnv = *env;
+    strcat(aux, thisEnv);
```
Comment (pavel-jares-bcm) [inline src/main.c:1314]: Rather to use strcpy and the dont clean aux

File: src/main.c (hunk 3 above)
Comment (pablocarle) [reply src/main.c]: sure, it was because the command is get-launch-components, to follow the same as the similar function for the prepare-instance

File: src/main.c (hunk 4 above)
Comment (pablocarle) [reply src/main.c:1326]: I'm not sure what you mean here, this code is from the previous version, just moved it up

File: src/main.c (hunk 5 above)
Comment (pablocarle) [reply src/main.c:1314]: this is code from the previous version and it works, I'd rather keep it as it is, unless there's some issue.

**Review by pavel-jares-bcm — APPROVED** [review]

File: src/main.c (hunk 4 above)
Comment (pavel-jares-bcm) [reply src/main.c:1326]: The JSON content is solved by `jsonToString`. The potential issue could come from `shared_uss_env[idx++] = thisEnv;`.

The proper solution there should probably be like this: 
```c
if (*thisEnv != '\"') {
 newstr = malloc(?);
 newstr[0] = 0; 
 strcat(newstr, key);
 strcat(newstr, "=");
 strcat(newstr, escapeString(thisEnv + length);
 length = newstr;
}
```

...anyway, I guess it is a bug, that could be solved in an issue. The workaround could be to use a different form in STC. And from another hand, it is pretty rear to set especially in this way string value with a quote.

Comment (pablocarle) [reply src/main.c:1326]: opened an issue based on testing done with these scenarios https://github.com/zowe/launcher/issues/76

**Comment by 1000TurquoisePogs** [comment]
Thank you, this is looking good to me as well so I'm going to merge it due to @pj892031 's approval.
