### PR TITLE
Fix path corruption

### LINKED ISSUE #619: runtimeDirectory path corruption configuration
From Madeleine Dudek in Slack:

Okay, so ... We use Zowe 2.9, we installed our own apps and UMS, and ever since we have UMS, the Zowe server start gets an error:
cd: /S0W1/var/zowe/nightly/components/app-server/bin/configure.sh 30: .: /S0W1/var/zowe/nightly0/components/app-server/share/zlux-app-server/bin/init: EDC5129I No such file or directory. (errno2=0x0594003D)
which probably prevents app-server from configuring a few things ... (the path should say nightly, not nightly0)
This happens after our apps and UMS do their validations, so to rule out that one of ours caused that error, I did some Zowe "elevator testing" (up and down and up and down ...)
I removed our apps and restarted Zowe: no error.
I re-added one app and restarted Zowe: slightly different error:
cd: /S0W1/var/zowe/nightly/components/app-server/bin/configure.sh 30: .: /S0W1/var/zowe/nightlyï¿½/components/app-server/share/zlux-app-server/bin/init: EDC5129I No such file or directory. (errno2=0x0594003D)
I removed the first and added the other app and restarted Zowe: 2nd error
I removed most of our app's validation (commented it out) and restarted Zowe: no error
I re-added the validation stuff bit by bit until it all was complete again,  and restarted Zowe every time: no error, not even with the full code. :face_with_raised_eyebrow: At this point stuff stopped making sense.
I re-added the remainder of our apps, restarted Zowe and the first error (nightly0) returned.
I specified logLevel: trace and restarted Zowe once more. With all this extra outputting, stuff seems to happen in a different sequence.
Now app-server's configure.sh seems to run before our own apps' validation, at least according to the log, and it ran into the error again.
Interestingly, the only variable with the wrong path (nightly0 instead of nightly) is ROOT_DIR, which is not even used by app-server's scripts. I was not able to track down where $ROOT_DIR's value becomes $ZWE_zowe_runtimeDirectory's value. Any ideas?
(side note: my search unearthed a different typo: $ZOE_ROOT_DIR in <ZWE_zowe_runtimeDirectory>/components/app-server/share/zlux-app-server/bin/zlux-install-script.sh (though that scripts seems to be unused))

### PR DESCRIPTION
**Pull request by 1000TurquoisePogs**
Thanks to Keisuke Kamada at Rocket spotting the reason for the bug and suggesting this patch
Fixes https://github.com/zowe/zss/issues/619

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -412,11 +412,13 @@ static void set_shared_uss_env(ConfigManager *configmgr) {
 
     int length = index - thisEnv;
     char *key = malloc(length + 1);
+    memset(key, 0, sizeof(*key));
```
Comment (lchudinov) [inline src/main.c]: `sizeof(*key)` is equivalent to `sizeof(char)` that is only 1 byte long. Please replace `sizeof(*key)` with `length + 1`.

File: src/main.c [hunk 2]
```diff
@@ -412,11 +412,13 @@ static void set_shared_uss_env(ConfigManager *configmgr) {
...
     strncpy(key, thisEnv, length);
     
     if (!arrayListContains(list, key)) {
       arrayListAdd(list, key);
       char *new_env = malloc(strlen(thisEnv));
+      memset(new_env, 0, sizeof(*new_env));
```
Comment (lchudinov) [inline src/main.c]: `sizeof(*new_env)` is only 1 byte long.

**Review by JoeNemo — APPROVED** [review]
Approved.
